function [ cluster_matrix ] = generateItemClusRMatrix(...
    FDT_mode, ...
    user_cluster, ...
    item_sim_matrix, weight,...
    test_UI_matrix )
    clusterNum = size(user_cluster, 2);
    testItemNum = size(test_UI_matrix, 2);
    cluster_matrix = zeros(clusterNum, testItemNum);   % (clusters, items)
    
    for i = 1 : clusterNum
        if FDT_mode
            single_cluster_matrix  = test_UI_matrix(user_cluster{i}, :);
            cluster_matrix(i, :) = sum(single_cluster_matrix, 1) ...
                ./ (1e-9 + sum((single_cluster_matrix~=0), 1));
        else
            score_matrix = (test_UI_matrix(user_cluster{i}, :)     * item_sim_matrix)...
                                                    ./ ...
                          ((test_UI_matrix(user_cluster{i}, :)~=0) * item_sim_matrix);
            single_cluster_matrix  = test_UI_matrix(user_cluster{i}, :)...
                                        + ...
                                 weight * (test_UI_matrix(user_cluster{i}, :) == 0) .* score_matrix;
            cluster_matrix(i, :) = sum(single_cluster_matrix, 1) ...
                                    ./ ...
            (sum(weight*(test_UI_matrix(user_cluster{i}, :)==0), 1) + sum((test_UI_matrix(user_cluster{i}, :)~=0), 1));
        end
    end
end

